import { Fraunces } from 'next/font/google';

const fraunces = Fraunces({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={fraunces.className}>{children}</body>
		</html>
	);
}
